### PR TITLE
Pull request template has been added

### PR DESCRIPTION
**Pull request by anwarhossain1**

### CODE REVIEW

**Comment by jbampton** [comment]
Pull requests should be done from another feature branch not main.

This PR has conflicts.

The PR template is empty. 

Closing.

**Comment by jbampton** [comment]
Hey @anwarhossain1  https://github.com/tiimgreen/github-cheat-sheet

**Comment by anwarhossain1** [comment]
Checking it.

**Comment by anwarhossain1** [comment]
Is it alright now?

**Comment by anwarhossain1** [comment]
Hey how are you doing?

**Pull request closed without merging**
