### PR TITLE
Fix Super-Linter Bash linting errors

### PR DESCRIPTION
**Pull request by BDadmehr0**
### Description

This pull request updates the Bash build script to resolve linting issues flagged by `ShellCheck` and improves its overall robustness. The changes enhance readability, modernize command usage, and ensure compliance with best practices.

### Related Issue

This PR addresses **[Issue #321](https://github.com/SalamLang/Salam/issues/321)** (Super-Linter Bash linting errors).

### Proposed Changes

- Replaced indirect exit code checks (`$?`) with direct command checks using `if !` to resolve `SC2181`.
- Updated glob patterns to prefix with `./` to resolve `SC2035` and avoid unintended matches.
- Enhanced readability by restructuring sections and adding spacing.
- Preserved functionality, including optional cleanup of object files.

### CODE REVIEW

**Comment by BaseMax** [comment]
cc @jbampton

**Comment by jbampton** [comment]
Why closed?

**Comment by jbampton** [comment]
Hey @BDadmehr0  I just added you to the triage team

https://github.com/orgs/SalamLang/teams

https://github.com/orgs/SalamLang/teams/triage/repositories

Screenshot from 2024-11-26 01-00-45

**Comment by BDadmehr0** [comment]
> Hey @BDadmehr0 I just added you to the triage team
> 
> https://github.com/orgs/SalamLang/teams
> 
> https://github.com/orgs/SalamLang/teams/triage/repositories

Thanks for adding me to the triage team! Could you please let me know more about my responsibilities or next steps?

**Comment by jbampton** [comment]
Hey @BDadmehr0 basically you just got higher permissions and we hope you will help out more.

By triage we mean interact with contributors on issues and PRs and also fill in the missing details for:

- Assignees
- Labels
- Projects
- Milestones

Some of those get auto filled on PRs but we can always make that smarter too.

Example shown below

Thanks once again.

Screenshot from 2024-11-26 05-59-40

**Pull request closed without merging**
