### PR TITLE
Updated pull request template added

### PR DESCRIPTION
**Pull request by anwarhossain1**

### CODE REVIEW

**Comment by erfangnu** [comment]
need your input mate @jbampton

**Comment by erfangnu** [comment]
@anwarhossain1 please follow what John said

**Comment by erfangnu** [comment]
**Conflicting files
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/custom.md**

**Comment by anwarhossain1** [comment]
@erfangnu mate, those changes are as per the instructions.

**Comment by jbampton** [comment]
We already have the issue templates please remove those files

**Comment by erfangnu** [comment]
image

```
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/SalamLang/Salam/pull/126/conflicts) or the  to resolve conflicts.
Conflicting files
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/custom.md
```

**Comment by erfangnu** [comment]
???

**Comment by erfangnu** [comment]
?

**Review by anwarhossain1 — COMMENTED** [review]
Conflicting files
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/custom.md removed

**Comment by anwarhossain1** [comment]
Sorry for the delay. I thought someone would delete those files. I deleted those files and gave a request.

**Comment by erfangnu** [comment]
@jbampton pls chec

**Comment by erfangnu** [comment]
ah my bad.

**Comment by anwarhossain1** [comment]
finally :D

**Pull request merged**
