### PR TITLE
B dadmehr0 clang format

### PR DESCRIPTION
**Pull request by BDadmehr0**
**Summary**:

This pull request adds the `mirrors-clang-format` package to the `.pre-commit-config.yaml` file with version v13.0.0. The configuration is set up to use `clang-format` with the `--style=file` argument, which takes a style configuration file as input.

**Details**:

- Added `mirrors-clang-format` package to `.pre-commit-config.yaml`.
- Configured clang-format with the `--style=file` argument.
- You can manually format the code by running: `clang-format -i src/*.c src/*.h`.
- Added commands to `.git/hooks/pre-commit` for automatic code formatting before each commit.
-  Successfully formatted all code files using the above command.
-  Encountered issues with spell check, which interfered with the process, so it was removed.

Feel free to adjust any specifics as needed!

### CODE REVIEW

**Review by jbampton — COMMENTED** [review]
We were going to use tabs for indents in C files

@BaseMax

**Comment by BaseMax** [comment]
I noticed you deleted https://github.com/codespell-project/codespell from the pre-commit configuration and added https://github.com/pre-commit/mirrors-clang-format. I'm fine with adding the new one, but why was the other one removed? John added it earlier, so I’m wondering if we still need it. Could you provide an explanation? @BDadmehr0 @jbampton

**Comment by BaseMax** [comment]
> We were going to use tabs for indents in C files

He can change its configuration and use tabs rather than spaces. I guess it should be easy and he can do it. right? @jbampton

**Comment by BaseMax** [comment]
@BDadmehr0 Thank you so much for your contribution! I'm glad to see your involvement in the project.

I'd love to hear how you came across the project—it must be an interesting story.

Once you've addressed the mentioned issues, either John or I will review and merge your request.

Happy coding!
Max

**Comment by BDadmehr0** [comment]
> I noticed you deleted https://github.com/codespell-project/codespell from the pre-commit configuration and added https://github.com/pre-commit/mirrors-clang-format. I'm fine with adding the new one, but why was the other one removed? John added it earlier, so I’m wondering if we still need it. Could you provide an explanation? @BDadmehr0 @jbampton

I removed codespell because it was giving errors that I was struggling with for several hours and couldn't resolve. Errors like the following:

``` bash
identity.................................................................Passed
- hook id: identity
- duration: 0.12s

.clang-format
src/build-linux.sh
src/salam-wa.js
.pre-commit-config.yaml
src/build-webassembly.sh
src/salam-wa.html

Check hooks apply to the repository......................................Passed
check for added large files..............................................Passed
check for case conflicts.................................................Passed
check that executables have shebangs.....................................Passed
check for merge conflicts................................................Passed
check that scripts with shebangs are executable..........................Passed
check vcs permalinks.....................................................Passed
check yaml...............................................................Passed
detect destroyed symlinks................................................Passed
detect aws credentials...................................................Passed
detect private key.......................................................Passed
fix end of files.........................................................Passed
fix utf-8 byte order marker..............................................Passed
forbid submodules....................................(no files to check)Skipped
mixed line ending........................................................Passed
trim trailing whitespace.................................................Passed
Run codespell............................................................Failed
- hook id: codespell
- exit code: 65

src/salam-wa.js:70: direcly ==> directly
src/salam-wa.js:1513: defintion ==> definition
src/salam-wa.js:2952: existant ==> existent
src/salam-wa.html:242: ACi ==> acpi

Markdown Link Check..................................(no files to check)Skipped
Run markdownlint.....................................(no files to check)Skipped
Run yamllint.............................................................Passed
clang-format.........................................(no files to check)Skipped
```

I couldn't change the issues that codespell pointed out, such as `src/salam-wa.html:242`. Changing these words would break the entire code.

**Comment by BaseMax** [comment]
```
src/salam-wa.js:70: direcly ==> directly
src/salam-wa.js:1513: defintion ==> definition
src/salam-wa.js:2952: existant ==> existent
src/salam-wa.html:242: ACi ==> acpi
```

It appears that the pre-commit spell checker is flagging some misspellings in the .js and .html files, but these aren't relevant. We can safely ignore these files in the spell checker configuration. The `salam-wa.js` and `salam-wa.html` files should be excluded from the pre-commit spell check.

**Comment by BDadmehr0** [comment]
> @BDadmehr0 Thank you so much for your contribution! I'm glad to see your involvement in the project.
> 
> I'd love to hear how you came across the project—it must be an interesting story.
> 
> Once you've addressed the mentioned issues, either John or I will review and merge your request.
> 
> Happy coding! Max

I was working on my personal project called 'Internet Azad,' which is focused on distributing VLESS, Trojan, and SS protocols, and I was searching for subscription links using hashtags like VLESS, etc. Then I came across the word 'salam,' and after reading the repo description, I realized what an awesome project it is!

**Comment by BDadmehr0** [comment]
> It appears that the pre-commit spell checker is flagging some misspellings in the .js and .html files, but these aren't relevant. We can safely ignore these files in the spell checker configuration. The `salam-wa.js` and `salam-wa.html` files should be excluded from the pre-commit spell check.

So, does that mean I can add codespell back again?

**Comment by BaseMax** [comment]
> So, does that mean I can add codespell back again?

Yes please, and salam-wa.js and salam-wa.html files should be excluded from the pre-commit spell check.

**Comment by BaseMax** [comment]
You can find more about `exclude`  https://pre-commit.com/

```
# ...
    -   id: my-hook
        exclude: |
            (?x)^(
                path/to/file1.py|
                path/to/file2.py|
                path/to/file3.py
            )$
```

**Comment by BDadmehr0** [comment]
I'm working on it.

**Comment by BaseMax** [comment]
Any updates?

**Comment by BaseMax** [comment]
```
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/SalamLang/Salam/pull/219/conflicts) or the  to resolve conflicts.
Conflicting files
src/generator.c
src/generator.h
src/main.c
```

**Comment by BDadmehr0** [comment]
> Any updates?

I'm working on adding codespell and resolving the conflicts, and I will update soon.

**Comment by BDadmehr0** [comment]
The changes have been made and the conflicts have been resolved. Please review. @BaseMax

**Comment by BaseMax** [comment]
```
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/SalamLang/Salam/pull/219/conflicts) or the  to resolve conflicts.
Conflicting files
src/generator.c
src/generator.h
src/main.c
```

**Comment by BaseMax** [comment]
Thank you so much for your valuable contributions!

Our internal editor is hosted at https://editor.salamlang.ir/, and the documentation can be found at https://docs.salamlang.ir/.

The website is currently under development, but it will be live soon.

We appreciate your comments and feedback.

Happy coding! :)

**Comment by jbampton** [comment]
https://github.com/torvalds/linux/blob/d1f2d51b711a3b7f1ae1b46701c769c1d580fa7f/kernel/acct.c#L80

The Linux kernel uses tabs for indents in C files. 

This PR should not have been merged.

**Pull request merged**
