### PR TITLE
V3

### PR DESCRIPTION
**Pull request by BaseMax**
### Description

Please include a brief description of the changes introduced by this pull request.

### Related Issue

If this pull request addresses or resolves an existing issue, please reference it here.

### Proposed Changes

Outline the changes made in this pull request and explain their purpose.

### Checklist

- [ ] I have tested these changes locally.
- [ ] My code follows the project's coding style guidelines.
- [ ] I have reviewed my own code to ensure quality.
- [ ] Unnecessary comments were removed.

### Additional Notes

Add any additional notes or context about this pull request.

### CODE REVIEW

**Comment by BaseMax** [comment]
This branch has conflicts that must be resolved
 to resolve conflicts before continuing.
Conflicting files
b.sh
challenges/first/input.salam
challenges/first/output.html
output.html

**Review by jbampton — COMMENTED** [review]
A lot of files are deleted ?

**Comment by BaseMax** [comment]
yes, please undo required files for pre-commits and github actiots if you need to keep these. 
all other files, let's delete @jbampton

**Comment by BaseMax** [comment]
pls delete these `This branch has conflicts that must be resolved
 to resolve conflicts before continuing.
Conflicting files
b.sh
challenges/first/input.salam
challenges/first/output.html
output.html
`

**Comment by BaseMax** [comment]
merged

**Pull request merged**
