### PR TITLE
Abstract Malloc through macro

### PR DESCRIPTION
**Pull request by janus**
Abstract malloc through macro

### CODE REVIEW

**Review by erfangnu — DISMISSED** [review]
okay cool

**Comment by erfangnu** [comment]
```
<<<<<<< AbstractMalloc
	ast_literal_t* res;
	CREATE_MEMORY_OBJECT(res, ast_literal_t, 1, "Error: interpreter_expression_binary<res> - Memory allocation error in %s:%d\n",  __FILE__, __LINE__);
	res->main = (struct ast_expression_t**) &expr;
=======
	ast_literal_t* res = (ast_literal_t*) malloc(sizeof(ast_literal_t));
	res->main = &expr;
>>>>>>> main
```

please fix @janus

**Comment by janus** [comment]
> ```
> <<<<<<< AbstractMalloc
> 	ast_literal_t* res;
> 	CREATE_MEMORY_OBJECT(res, ast_literal_t, 1, "Error: interpreter_expression_binary<res> - Memory allocation error in %s:%d\n",  __FILE__, __LINE__);
> 	res->main = (struct ast_expression_t**) &expr;
> =======
> 	ast_literal_t* res = (ast_literal_t*) malloc(sizeof(ast_literal_t));
> 	res->main = &expr;
> >>>>>>> main
> ```
> 
> please fix @janus

```
	ast_literal_t* res;
	CREATE_MEMORY_OBJECT(res, ast_literal_t, 1, "Error: interpreter_expression_binary<res> - Memory allocation error in %s:%d\n",  __FILE__, __LINE__);
	res->main = (struct ast_expression_t**) &expr;
```
The above is how it should look after corrected. But I don't think I have the right to fix such. Or which git command should I use?

**Comment by janus** [comment]
> ```
> <<<<<<< AbstractMalloc
> 	ast_literal_t* res;
> 	CREATE_MEMORY_OBJECT(res, ast_literal_t, 1, "Error: interpreter_expression_binary<res> - Memory allocation error in %s:%d\n",  __FILE__, __LINE__);
> 	res->main = (struct ast_expression_t**) &expr;
> =======
> 	ast_literal_t* res = (ast_literal_t*) malloc(sizeof(ast_literal_t));
> 	res->main = &expr;
> >>>>>>> main
> ```
> 
> please fix @janus

Fixed.

**Comment by erfangnu** [comment]
MERGED, THANKS. LGTM

**Pull request merged**
